## warmup excercise

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("practice.csv")
df

     name  marks  gender
0     Ali     85    Male
1  Hammad     92    Male
2  Ayesha     78  Female
3   Bilal     67    Male
4  Fatima     95  Female
5   Usman     73    Male
6  Zainab     88  Female

In [4]:
# some questions
# 1 display top three rows of dataset

df.head(3)

     name  marks  gender
0     Ali     85    Male
1  Hammad     92    Male
2  Ayesha     78  Female

In [5]:
# 2: last 3 rows

df.tail(3)

     name  marks  gender
4  Fatima     95  Female
5   Usman     73    Male
6  Zainab     88  Female

In [6]:
# 3: find shape of dataset

df.shape

(7, 3)

In [7]:
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Number of rows: 7
Number of columns: 3

In [ ]:
# 4:get information about the dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      str
 1   marks   7 non-null      int64
 2   gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

In [ ]:
# 5: check null values in the dataset
df.isnull().sum() # column wise check axis= 0

name      0
marks     0
gender    0
dtype: int64

In [ ]:
df.isnull().sum(axis = 1) # row wise check

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [ ]:
# 6: get overall statistics of the dataset
df.describe() # only applies to numerical

           marks
count   7.000000
mean   82.571429
std    10.277113
min    67.000000
25%    75.500000
50%    85.000000
75%    90.000000
max    95.000000

In [ ]:
df.describe(include= "all") # also appliesto categorical cols

       name      marks gender
count     7   7.000000      7
unique    7        NaN      2
top     Ali        NaN   Male
freq      1        NaN      4
mean    NaN  82.571429    NaN
std     NaN  10.277113    NaN
min     NaN  67.000000    NaN
25%     NaN  75.500000    NaN
50%     NaN  85.000000    NaN
75%     NaN  90.000000    NaN
max     NaN  95.000000    NaN

In [18]:
# 7: Find unique values from the gender column.
df["gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [19]:
# find the no. of unique values from the gender column.
df["gender"].nunique()

2

In [20]:
# display count of unique values in gender column
df["gender"].value_counts()

gender
Male      4
Female    3
Name: count, dtype: int64